### ISSUE TITLE
Kjaro's Band do not deal AoE damage

### ISSUE THREAD

**Issue by Judgy53** [Goorakh/PizzaClientLagFix#1]
I noticed my friend and I were really struggling with Mythrix P4 skip since we installed this mod. We did a bit of testing and noticed the lingering AoE from Kjaro's band does not deal any damage, even as host. 

I might be wrong, but I think Kjaro's Band lingering AoE uses `OverlapAttack` to deal damage, and something about the authority check does not work on enemies.

**Comment by Goorakh** [comment]
Oop! No clue what that was about. But it's fixed now. Thanks! :)
